import React from "react";
import { ComponentMeta } from "@storybook/react";
import { MatchList } from "./MatchList";
import { Container } from "@mui/material";

export default {
  title: "Components/MatchList",
  component: MatchList,
  decorators: [
    (Story) => (
      <Container maxWidth="lg">
        <Story />
      </Container>
    ),
  ],
} as ComponentMeta<typeof MatchList>;

export const list = () => (
  <MatchList
    dateItems={[
      {
        id: "1",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  teamName: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  teamName: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "2",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
    ]}
  />
);

export const paginatedList = () => (
  <MatchList
    dateItems={[
      {
        id: "1",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  inhibitorKills: 19,
                  baronKills: 19,
                  didWin: true,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  inhibitorKills: 19,
                  baronKills: 19,
                  didWin: false,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "2",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "13",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "452",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "233",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "521",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "2234",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "5233",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "23451",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "1235",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "32345",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "34561",
        date: "23-01-2020",
        gamesPlayed: 3,
        teamsParticipated: 1,
        organization: "Leagou",
        updated: 1628613368790,
        details: [
          {
            id: "1",
            matches: [
              {
                match_id: "1",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "2435",
        date: "26-01-2020",
        gamesPlayed: 9,
        teamsParticipated: 4,
        organization: "Monal",
        updated: 1628613328390,
        details: [
          {
            id: "2",
            matches: [
              {
                match_id: "2",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "35223",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3522343",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 11,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "31223",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "352453",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "323523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "35254363",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  didWin: false,
                  inhibitorKills: 9,
                  baronKills: 19,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3756523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "352453",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3568523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3523567",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3524573",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3567523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3527683",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "374577523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "334523",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "3587623",
        date: "28-01-2020",
        gamesPlayed: 8,
        teamsParticipated: 4,
        organization: "Microsoft",
        updated: 1628613368790,
        details: [
          {
            id: "3",
            matches: [
              {
                match_id: "3",
                matchDay: 2,
                matchWeek: "Week 1",
                gameLength: "29:23",
                teamA: {
                  team_id: "1",
                  name: "Not",
                  totalPoints: 25,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamB: {
                  team_id: "2",
                  name: "Some",
                  totalPoints: 31,
                  teamKills: 23,
                  dragonKills: 15,
                  riftHeralds: 11,
                  turretKills: 10,
                  baronKills: 19,
                  didWin: false,
                  inhibitorKills: 9,
                },
                teamAMembers: [
                  {
                    teamMember_id: 1,
                    team: "Teamname",
                    role: "cool role",
                    name: "Blonk",
                    totalPoints: 15,
                    championName: "blink",
                    kills: 4,
                    assists: 95,
                    deaths: 9,
                    creepScore: 123,
                  },
                ],
                teamBMembers: [
                  {
                    teamMember_id: 2,
                    name: "Manop",
                    team: "Teamname",
                    role: "cool role",
                    totalPoints: 75,
                    championName: "mapol",
                    kills: 7,
                    assists: 45,
                    deaths: 2,
                    creepScore: 723,
                  },
                ],
              },
            ],
          },
        ],
      },
    ]}
  />
);
